### ISSUE TITLE
Could not initialize sensor with ESP-IDF

### ISSUE THREAD

**Issue by ameerhazo** [gschorcht/ccs811-esp-idf#3]
Hi, I'm trying to use this sensor library with ESP-IDF. The example code builds fine but the sensor isnt being initialized. I've gone through the i2c init function and nothing seems to be different compared to the i2c example provided by Espressif. Any help would be greatly appreciated.

**Comment by Stormhand** [comment]
Hi, I'm using this lib for years, now with idf v4.2 but I changed the data var in ccs811.c on line 347 to
`uint8_t data[4]  = { hum  >> 8, hum  & 0xff,    temp >> 8, temp & 0xff };`

**Comment by ameerhazo** [comment]
Hi @Stormhand, thank you for taking your time to help me with my problem. I'm using idf 4.3 atm. Did you change anything else in the example code? The code builds fine and I've checked my connections on my ESP32. I'm gonna try your suggestion now and see how it goes. I'll get back to you with an update in a few minutes. Thanks again :D

**Comment by ameerhazo** [comment]
@Stormhand Thanks for the help :D The sensor is reading like it is supposed to. Did your ESP32 read the sensor before you made the changes to the code? Thanks a lot for the help.

**Comment by Stormhand** [comment]
No, i had the same problem as you. It seema that the data bits for humidity and temp are flipped. Im glad its working now :)

**Comment by ameerhazo** [comment]
@Stormhand Hi Stormhand, I've been testing the sensor for a few days and it runs quite nicely. Have you tried running this sensor on the same bus as another i2c sensor? I would assume that it wouldnt work that well because the code doesnt include mutexes or sempahores for the FreeRTOS to schedule when the write and read actions of this sensor is done.

**Comment by Stormhand** [comment]
> @Stormhand Hi Stormhand, I've been testing the sensor for a few days and it runs quite nicely. Have you tried running this sensor on the same bus as another i2c sensor? I would assume that it wouldnt work that well because the code doesnt include mutexes or sempahores for the FreeRTOS to schedule when the write and read actions of this sensor is done.

Hi, im using it together with bme280 flawlessly but to be honest i dont remember if i changed something else because i flashed it 2 years ago.

**Comment by ameerhazo** [comment]
@Stormhand Thats good to hear. Did you use the ESP-IDF sensor library by UncleRus for the BME280 to use on the ESP32?

**Comment by Stormhand** [comment]
@ameerhazo no, im using this https://github.com/BoschSensortec/BME280_driver with some wrappers, because that is what i found back then.

**Comment by ameerhazo** [comment]
@Stormhand Oh cool. Always nice using the official one.
